# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seed_rl.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rseed_rl.proto\"-\n\x0cResetRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x05\x12\x0b\n\x03obs\x18\x02 \x01(\t\"`\n\x0b\x43\x61llRequest\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x01(\x05\x12\x0b\n\x03obs\x18\x02 \x01(\t\x12\x0e\n\x06reward\x18\x03 \x01(\x02\x12\x0c\n\x04\x64one\x18\x04 \x01(\t\x12\x14\n\x0crequest_type\x18\x05 \x01(\t\"\"\n\x10\x44iscreteGymReply\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x05\x32g\n\x06SeedRL\x12)\n\x05Reset\x12\r.ResetRequest\x1a\x11.DiscreteGymReply\x12\x32\n\x0f\x44iscreteGymStep\x12\x0c.CallRequest\x1a\x11.DiscreteGymReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seed_rl_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESETREQUEST._serialized_start=17
  _RESETREQUEST._serialized_end=62
  _CALLREQUEST._serialized_start=64
  _CALLREQUEST._serialized_end=160
  _DISCRETEGYMREPLY._serialized_start=162
  _DISCRETEGYMREPLY._serialized_end=196
  _SEEDRL._serialized_start=198
  _SEEDRL._serialized_end=301
# @@protoc_insertion_point(module_scope)
